name: Build and Deploy Code prod
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: deploy to ubuntu server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.PROD_HOST}}
          username: ${{secrets.PROD_USERNAME}}
          password: ${{secrets.PROD_PASSWORD}}
          port: ${{secrets.PROD_PORT}}
          key: ${{secrets.PROD_KEY}}

          script: |
            cd app/src
            git pull 
            echo ${{secrets.PROD_PASSWORD}} | sudo -S systemctl restart fastapi 

            
            


 
